### ISSUE TITLE
Allow CFF subroutinization without specialization

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/ufo2ft#385]
I have a font that I was subroutinizing with cffsubr, now after switching the the latest ufo2ft beta with the new cffsubr I get files that are 2 to 3KB larger (not a big deal, around 0.5% from the total file size).

If I force `optimize` to False I get the exact same files I had before: 
https://github.com/googlefonts/ufo2ft/blob/057b726a5bf327bd33a1f2c6fdf40edb76155b9f/Lib/ufo2ft/outlineCompiler.py#L1095

**Comment by anthrotype** [comment]
Hm that's strange. Maybe cffsubr (via tx) applies slightly different nominal/default width optimizations and specializations than fonttools', which end up modifying the resulting subroutines?

The problem is we are using a single `optimizeCFF` IntEnum parameter that goes from NONE, through SPECIALIZE and then SUBROUTINIZE in a logical increasing order.

I don't know we can introduce that change.

**Comment by anthrotype** [comment]
Also, as you know, when applying subroutinization via cffsubr the specialization is also always performed and can't be switched off -- but I guess that's now you're asking (i.e. a subroutinized font without specialization), rather you would like the specialization _and_ subroutinization be performed by the same cffsubr tool.

**Comment by anthrotype** [comment]
maybe, if we move the charstring specialization to the postProcessor stage, we could only do it for compreffor, but skip it if cffsubr is selected, since it will do it for us anyway. I'll see if I can do that.

**Comment by anthrotype** [comment]
@khaledhosny can you post an example of the differences you mentioned? I'd like to understand why this happens, before jumping in reorganizing the code.

**Comment by khaledhosny** [comment]
Apparently I manged to confuse myself, the original files are the bigger ones 🤦 

Sorry for the embarrassing mistake!
