### ISSUE TITLE
Cross-script kerning

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/ufo2ft#808]
Since https://github.com/googlefonts/ufo2ft/pull/679, kerning pairs are split per-script, under the assumption that OpenType layout is not applied across scripts.

As it turns out, there are more than one implementation that applies at least kerning across scripts (I have tested only Latin, Greek, Cyrillic, and Coptic, handling for other scripts might be different):
* CoreText applies kerning across the 4 tested scripts.
* InDesign’s Adobe Paragraph/Single-line Composer (see below)
* I’m told DirectWrite shapes Latin, Greek, and Cyrillic together, though I couldn’t manage to find a Windows application that shows this behavior.

There are also more than one orthography that uses a mix of scripts, so the issue here has potentially practical implications and not only theoretical ones:
* Sliammon language: [uses Greek chi and theta mixed with Latin](https://www.firstvoices.com/tlaamin).
* Heiltsuk alphabet: [uses Greek lambda and barred lambda mixed with Latin](https://www.omniglot.com/writing/heiltsuk.htm)

Since the motivation for https://github.com/googlefonts/ufo2ft/pull/679 was to optimize lookup sizes, and optimizations shouldn’t break functionality, I suggest to either:
* Revert this change and accept the sub-optimal lookup sizes
* Make the per-script behavior an opt-in
* Use a heuristic, e.g. if there are kerning pairs involving multiple scripts, keep these (or the kerning of involved scripts in general) in one lookup and register it for all the involved scripts.

Here are three fonts that include a couple of Latin, Greek, Cyrillic, and Coptic glyphs, with class kerning between them (all first glyphs in one class, and all second glyphs in another). The first font has the kerning lookup under DFLT script as well as script-specific tags, the second does not have it under DFLT, and the third has it under DFLT only: [CrossScriptKerningFonts.zip](https://github.com/googlefonts/ufo2ft/files/13762669/CrossScriptKerningFonts.zip)

If kerning is applied, the text should appear solid with no space between the triangular shapes.

Here are the testing results for the string “AVАVΑVⲀVAУАУΑУⲀУAΥАΥΑΥⲀΥAⲨАⲨΑⲨⲀⲨ”:
* Pages: works the same for all three fonts
  ![Pages](https://github.com/googlefonts/ufo2ft/assets/93914/1b11fdd5-3f04-442a-a5ee-8a3cdcc94be8)
* InDesign (Adobe Paragraph Composer): seems to require the lookup under DFLT script
  ![InDesign](https://github.com/googlefonts/ufo2ft/assets/93914/debf4de4-c076-4101-a85f-3bebf561cd65)
* Firefox (and basically every other application): 
  ![Firefox](https://github.com/googlefonts/ufo2ft/assets/93914/83faee32-a5dd-4a22-8dde-8e431be67639)

**Comment by behdad** [comment]
Let's file an HB issue as well...

**Comment by belluzj** [comment]
Kindof related:
* https://github.com/googlefonts/ufo2ft/pull/787
* https://github.com/googlefonts/ufo2ft/pull/788

In the GPOS optimization code, instead of creating one lookup per script, we create one subtable per script (and don't change the lookup structure). That achieves the exact same behaviour as before the optimization, and it gets almost the same file size savings as splitting by script. The trade-off is that it doesn't speed up compilation, because we still start with building the gigantic all-scripts-together lookup, then we spend extra time analyzing it to split it into subtables.

Maybe the split-by-script code could try to split into subtables within the same lookup, instead of different lookups? The rules would be slightly different, as the subtables cannot apply to same glyph (first matching subtable wins), while several lookups can apply to the same glyph.

**Comment by anthrotype** [comment]
> Use a heuristic, e.g. if there are kerning pairs involving multiple scripts, keep these (or the kerning of involved scripts in general) in one lookup and register it for all the involved scripts.

I'd be inclined to opt for this latter solution. Would you like to work on a PR?

**Comment by khaledhosny** [comment]
> > Use a heuristic, e.g. if there are kerning pairs involving multiple scripts, keep these (or the kerning of involved scripts in general) in one lookup and register it for all the involved scripts.
> 
> I'd be inclined to opt for this latter solution. Would you like to work on a PR?

Excellent. I’ll try to work on something in this direction.
